/* Generated by scripts/generate-edge-campaign.mjs. Do not hand edit. */
import type { GeneratedCampaignEntry } from './types';
import asset_0_template from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/scenario.template.json?url";
import asset_0_instance from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/scenario.instance.json?url";
import asset_0_trace from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/scenario.trace.json.gz?url";
import asset_0_rubric from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/intent-rubric.json?url";
import asset_0_evidence from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/validation.json?url";
import asset_0_provenance from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/intent.json?url";
import asset_0_ambient from "../../../../examples/edge-cases/01-construction-chicane-reversing-truck/ambient.json?url";
import asset_1_template from "../../../../examples/edge-cases/02-police-roadside-stop/scenario.template.json?url";
import asset_1_instance from "../../../../examples/edge-cases/02-police-roadside-stop/scenario.instance.json?url";
import asset_1_trace from "../../../../examples/edge-cases/02-police-roadside-stop/scenario.trace.json.gz?url";
import asset_1_rubric from "../../../../examples/edge-cases/02-police-roadside-stop/intent-rubric.json?url";
import asset_1_evidence from "../../../../examples/edge-cases/02-police-roadside-stop/validation.json?url";
import asset_1_provenance from "../../../../examples/edge-cases/02-police-roadside-stop/intent.json?url";
import asset_1_ambient from "../../../../examples/edge-cases/02-police-roadside-stop/ambient.json?url";
import asset_2_template from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/scenario.template.json?url";
import asset_2_instance from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/scenario.instance.json?url";
import asset_2_trace from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/scenario.trace.json.gz?url";
import asset_2_rubric from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/intent-rubric.json?url";
import asset_2_evidence from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/validation.json?url";
import asset_2_provenance from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/intent.json?url";
import asset_2_ambient from "../../../../examples/edge-cases/03-red-light-ambulance-preemption/ambient.json?url";
import asset_3_template from "../../../../examples/edge-cases/04-child-emerging-behind-bus/scenario.template.json?url";
import asset_3_instance from "../../../../examples/edge-cases/04-child-emerging-behind-bus/scenario.instance.json?url";
import asset_3_trace from "../../../../examples/edge-cases/04-child-emerging-behind-bus/scenario.trace.json.gz?url";
import asset_3_rubric from "../../../../examples/edge-cases/04-child-emerging-behind-bus/intent-rubric.json?url";
import asset_3_evidence from "../../../../examples/edge-cases/04-child-emerging-behind-bus/validation.json?url";
import asset_3_provenance from "../../../../examples/edge-cases/04-child-emerging-behind-bus/intent.json?url";
import asset_3_ambient from "../../../../examples/edge-cases/04-child-emerging-behind-bus/ambient.json?url";
import asset_4_template from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/scenario.template.json?url";
import asset_4_instance from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/scenario.instance.json?url";
import asset_4_trace from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/scenario.trace.json.gz?url";
import asset_4_rubric from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/intent-rubric.json?url";
import asset_4_evidence from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/validation.json?url";
import asset_4_provenance from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/intent.json?url";
import asset_4_ambient from "../../../../examples/edge-cases/05-cyclist-occlusion-conflict/ambient.json?url";
import asset_5_template from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/scenario.template.json?url";
import asset_5_instance from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/scenario.instance.json?url";
import asset_5_trace from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/scenario.trace.json.gz?url";
import asset_5_rubric from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/intent-rubric.json?url";
import asset_5_evidence from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/validation.json?url";
import asset_5_provenance from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/intent.json?url";
import asset_5_ambient from "../../../../examples/edge-cases/06-wrong-way-vehicle-blind-approach/ambient.json?url";
import asset_6_template from "../../../../examples/edge-cases/07-protected-left-red-runner/scenario.template.json?url";
import asset_6_instance from "../../../../examples/edge-cases/07-protected-left-red-runner/scenario.instance.json?url";
import asset_6_trace from "../../../../examples/edge-cases/07-protected-left-red-runner/scenario.trace.json.gz?url";
import asset_6_rubric from "../../../../examples/edge-cases/07-protected-left-red-runner/intent-rubric.json?url";
import asset_6_evidence from "../../../../examples/edge-cases/07-protected-left-red-runner/validation.json?url";
import asset_6_provenance from "../../../../examples/edge-cases/07-protected-left-red-runner/intent.json?url";
import asset_6_ambient from "../../../../examples/edge-cases/07-protected-left-red-runner/ambient.json?url";
import asset_7_template from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/scenario.template.json?url";
import asset_7_instance from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/scenario.instance.json?url";
import asset_7_trace from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/scenario.trace.json.gz?url";
import asset_7_rubric from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/intent-rubric.json?url";
import asset_7_evidence from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/validation.json?url";
import asset_7_provenance from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/intent.json?url";
import asset_7_ambient from "../../../../examples/edge-cases/08-zipper-merge-lane-closure/ambient.json?url";
import asset_8_template from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/scenario.template.json?url";
import asset_8_instance from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/scenario.instance.json?url";
import asset_8_trace from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/scenario.trace.json.gz?url";
import asset_8_rubric from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/intent-rubric.json?url";
import asset_8_evidence from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/validation.json?url";
import asset_8_provenance from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/intent.json?url";
import asset_8_ambient from "../../../../examples/edge-cases/09-stalled-vehicle-beyond-sight/ambient.json?url";
import asset_9_template from "../../../../examples/edge-cases/10-officer-flashing-red-junction/scenario.template.json?url";
import asset_9_instance from "../../../../examples/edge-cases/10-officer-flashing-red-junction/scenario.instance.json?url";
import asset_9_trace from "../../../../examples/edge-cases/10-officer-flashing-red-junction/scenario.trace.json.gz?url";
import asset_9_rubric from "../../../../examples/edge-cases/10-officer-flashing-red-junction/intent-rubric.json?url";
import asset_9_evidence from "../../../../examples/edge-cases/10-officer-flashing-red-junction/validation.json?url";
import asset_9_provenance from "../../../../examples/edge-cases/10-officer-flashing-red-junction/intent.json?url";
import asset_9_ambient from "../../../../examples/edge-cases/10-officer-flashing-red-junction/ambient.json?url";
import asset_10_template from "../../../../examples/edge-cases/11-double-threat-crosswalk/scenario.template.json?url";
import asset_10_instance from "../../../../examples/edge-cases/11-double-threat-crosswalk/scenario.instance.json?url";
import asset_10_trace from "../../../../examples/edge-cases/11-double-threat-crosswalk/scenario.trace.json.gz?url";
import asset_10_rubric from "../../../../examples/edge-cases/11-double-threat-crosswalk/intent-rubric.json?url";
import asset_10_evidence from "../../../../examples/edge-cases/11-double-threat-crosswalk/validation.json?url";
import asset_10_provenance from "../../../../examples/edge-cases/11-double-threat-crosswalk/intent.json?url";
import asset_10_ambient from "../../../../examples/edge-cases/11-double-threat-crosswalk/ambient.json?url";
import asset_11_template from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/scenario.template.json?url";
import asset_11_instance from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/scenario.instance.json?url";
import asset_11_trace from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/scenario.trace.json.gz?url";
import asset_11_rubric from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/intent-rubric.json?url";
import asset_11_evidence from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/validation.json?url";
import asset_11_provenance from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/intent.json?url";
import asset_11_ambient from "../../../../examples/edge-cases/12-fire-engine-gridlock-escape/ambient.json?url";

export const GENERATED_CAMPAIGN_ENTRIES: readonly GeneratedCampaignEntry[] = [
  { ...{"ordinal":1,"stableId":"ec-01-01-construction-chicane-reversing-truck-v2","slug":"01-construction-chicane-reversing-truck","title":"Construction Chicane with a Reversing Truck","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"belmont-research-center","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_0_template, "instanceUrl": asset_0_instance, "traceUrl": asset_0_trace, "rubricUrl": asset_0_rubric, "evidenceUrl": asset_0_evidence, "provenanceUrl": asset_0_provenance, "ambientUrl": asset_0_ambient } },
  { ...{"ordinal":2,"stableId":"ec-02-02-police-roadside-stop-v2","slug":"02-police-roadside-stop","title":"Police Roadside Stop with a Blocked Shoulder","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_1_template, "instanceUrl": asset_1_instance, "traceUrl": asset_1_trace, "rubricUrl": asset_1_rubric, "evidenceUrl": asset_1_evidence, "provenanceUrl": asset_1_provenance, "ambientUrl": asset_1_ambient } },
  { ...{"ordinal":3,"stableId":"ec-03-03-red-light-ambulance-preemption-v2","slug":"03-red-light-ambulance-preemption","title":"Red-Light Ambulance Preemption","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_2_template, "instanceUrl": asset_2_instance, "traceUrl": asset_2_trace, "rubricUrl": asset_2_rubric, "evidenceUrl": asset_2_evidence, "provenanceUrl": asset_2_provenance, "ambientUrl": asset_2_ambient } },
  { ...{"ordinal":4,"stableId":"ec-04-04-child-emerging-behind-bus-v2","slug":"04-child-emerging-behind-bus","title":"Child Emerging from Behind a Bus","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_3_template, "instanceUrl": asset_3_instance, "traceUrl": asset_3_trace, "rubricUrl": asset_3_rubric, "evidenceUrl": asset_3_evidence, "provenanceUrl": asset_3_provenance, "ambientUrl": asset_3_ambient } },
  { ...{"ordinal":5,"stableId":"ec-05-05-cyclist-occlusion-conflict-v2","slug":"05-cyclist-occlusion-conflict","title":"Occluded Cyclist at a Garage Exit","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_4_template, "instanceUrl": asset_4_instance, "traceUrl": asset_4_trace, "rubricUrl": asset_4_rubric, "evidenceUrl": asset_4_evidence, "provenanceUrl": asset_4_provenance, "ambientUrl": asset_4_ambient } },
  { ...{"ordinal":6,"stableId":"ec-06-06-wrong-way-vehicle-blind-approach-v2","slug":"06-wrong-way-vehicle-blind-approach","title":"Wrong-Way Vehicle on a Blind Approach","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"easterbrook-discovery-school","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_5_template, "instanceUrl": asset_5_instance, "traceUrl": asset_5_trace, "rubricUrl": asset_5_rubric, "evidenceUrl": asset_5_evidence, "provenanceUrl": asset_5_provenance, "ambientUrl": asset_5_ambient } },
  { ...{"ordinal":7,"stableId":"ec-07-07-protected-left-red-runner-v2","slug":"07-protected-left-red-runner","title":"Red-Light Runner Through a Protected Intersection","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"el-camino-road","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_6_template, "instanceUrl": asset_6_instance, "traceUrl": asset_6_trace, "rubricUrl": asset_6_rubric, "evidenceUrl": asset_6_evidence, "provenanceUrl": asset_6_provenance, "ambientUrl": asset_6_ambient } },
  { ...{"ordinal":8,"stableId":"ec-08-08-zipper-merge-lane-closure-v2","slug":"08-zipper-merge-lane-closure","title":"Marshal-Controlled Lane Closure Merge","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_7_template, "instanceUrl": asset_7_instance, "traceUrl": asset_7_trace, "rubricUrl": asset_7_rubric, "evidenceUrl": asset_7_evidence, "provenanceUrl": asset_7_provenance, "ambientUrl": asset_7_ambient } },
  { ...{"ordinal":9,"stableId":"ec-09-09-stalled-vehicle-beyond-sight-v2","slug":"09-stalled-vehicle-beyond-sight","title":"Stalled Vehicle Beyond a Sight Constraint","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"el-camino-road","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_8_template, "instanceUrl": asset_8_instance, "traceUrl": asset_8_trace, "rubricUrl": asset_8_rubric, "evidenceUrl": asset_8_evidence, "provenanceUrl": asset_8_provenance, "ambientUrl": asset_8_ambient } },
  { ...{"ordinal":10,"stableId":"ec-10-10-officer-flashing-red-junction-v2","slug":"10-officer-flashing-red-junction","title":"Officer-Controlled Flashing-Red Junction","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_9_template, "instanceUrl": asset_9_instance, "traceUrl": asset_9_trace, "rubricUrl": asset_9_rubric, "evidenceUrl": asset_9_evidence, "provenanceUrl": asset_9_provenance, "ambientUrl": asset_9_ambient } },
  { ...{"ordinal":11,"stableId":"ec-11-11-double-threat-crosswalk-v2","slug":"11-double-threat-crosswalk","title":"Two-Stage Vulnerable-Road-User Crossing","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"el-camino-road","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_10_template, "instanceUrl": asset_10_instance, "traceUrl": asset_10_trace, "rubricUrl": asset_10_rubric, "evidenceUrl": asset_10_evidence, "provenanceUrl": asset_10_provenance, "ambientUrl": asset_10_ambient } },
  { ...{"ordinal":12,"stableId":"ec-12-12-fire-engine-gridlock-escape-v2","slug":"12-fire-engine-gridlock-escape","title":"Fire Engine Gridlock Escape Corridor","owner":"Codex curated edge-case suite","status":"strict-cli-validated-with-declared-adaptations","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"sumo-smoke-verified","rubric":"declared-runtime-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_11_template, "instanceUrl": asset_11_instance, "traceUrl": asset_11_trace, "rubricUrl": asset_11_rubric, "evidenceUrl": asset_11_evidence, "provenanceUrl": asset_11_provenance, "ambientUrl": asset_11_ambient } }
];
export const GENERATED_CAMPAIGN_DIAGNOSTICS: readonly string[] = [];
export const GENERATED_CAMPAIGN_MANIFEST_COUNT = 1;
