/* Generated by scripts/generate-edge-campaign.mjs. Do not hand edit. */
import type { GeneratedCampaignEntry } from './types';
import asset_0_template from "../../../../examples/edge-cases/blind-chicane-emerging-worker/scenario.template.json?url";
import asset_0_instance from "../../../../examples/edge-cases/blind-chicane-emerging-worker/instance.json?url";
import asset_0_trace from "../../../../examples/edge-cases/blind-chicane-emerging-worker/trace.json.gz?url";
import asset_0_rubric from "../../../../examples/edge-cases/blind-chicane-emerging-worker/intent-rubric.json?url";
import asset_0_evidence from "../../../../examples/edge-cases/blind-chicane-emerging-worker/simulation.json?url";
import asset_1_template from "../../../../examples/edge-cases/bus-occluded-child-signalized-crossing/scenario.template.json?url";
import asset_1_instance from "../../../../examples/edge-cases/bus-occluded-child-signalized-crossing/instance.json?url";
import asset_1_trace from "../../../../examples/edge-cases/bus-occluded-child-signalized-crossing/trace.json.gz?url";
import asset_1_rubric from "../../../../examples/edge-cases/bus-occluded-child-signalized-crossing/intent-rubric.json?url";
import asset_1_evidence from "../../../../examples/edge-cases/bus-occluded-child-signalized-crossing/simulation.json?url";
import asset_2_template from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/scenario.template.json?url";
import asset_2_instance from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/scenario.instance.json?url";
import asset_2_trace from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/scenario.trace.json.gz?url";
import asset_2_rubric from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/rubric.json?url";
import asset_2_evidence from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/evidence.json?url";
import asset_2_provenance from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/site.json?url";
import asset_2_ambient from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/ambient-sweep.json?url";
import asset_2_variations from "../../../../examples/edge-cases/contraflow-cyclist-garage-exit/site.json?url";
import asset_3_template from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/scenario.template.json?url";
import asset_3_instance from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/scenario.instance.json?url";
import asset_3_trace from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/scenario.trace.json.gz?url";
import asset_3_rubric from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/rubric.json?url";
import asset_3_evidence from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/evidence.json?url";
import asset_3_provenance from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/site.json?url";
import asset_3_ambient from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/ambient-sweep.json?url";
import asset_3_variations from "../../../../examples/edge-cases/wrong-way-sedan-blind-crest/site.json?url";
import asset_4_template from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/template.json?url";
import asset_4_instance from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/instance.baseline.json?url";
import asset_4_trace from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/trace.baseline.json.gz?url";
import asset_4_rubric from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/rubric.json?url";
import asset_4_evidence from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/evidence.baseline.json?url";
import asset_4_provenance from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/provenance.json?url";
import asset_4_variations from "../../../../examples/edge-cases/05-ambulance-gridlocked-intersection/sites.json?url";
import asset_5_template from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/template.json?url";
import asset_5_instance from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/instance.baseline.json?url";
import asset_5_trace from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/trace.baseline.json.gz?url";
import asset_5_rubric from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/rubric.json?url";
import asset_5_evidence from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/evidence.baseline.json?url";
import asset_5_provenance from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/provenance.json?url";
import asset_5_variations from "../../../../examples/edge-cases/06-dark-signal-conflicting-human-control/sites.json?url";
import asset_6_template from "../../../../examples/edge-cases/07-dooring-chain-tram/template.json?url";
import asset_6_instance from "../../../../examples/edge-cases/07-dooring-chain-tram/instance.json?url";
import asset_6_trace from "../../../../examples/edge-cases/07-dooring-chain-tram/trace.json.gz?url";
import asset_6_rubric from "../../../../examples/edge-cases/07-dooring-chain-tram/rubric.json?url";
import asset_6_evidence from "../../../../examples/edge-cases/07-dooring-chain-tram/result.json?url";
import asset_6_provenance from "../../../../examples/edge-cases/07-dooring-chain-tram/site-provenance.json?url";
import asset_6_ambient from "../../../../examples/edge-cases/07-dooring-chain-tram/ambient-sweep.json?url";
import asset_6_variations from "../../../../examples/edge-cases/07-dooring-chain-tram/site-matches.json?url";
import asset_7_template from "../../../../examples/edge-cases/08-runaway-shopping-cart/template.json?url";
import asset_7_instance from "../../../../examples/edge-cases/08-runaway-shopping-cart/instance.json?url";
import asset_7_trace from "../../../../examples/edge-cases/08-runaway-shopping-cart/trace.json.gz?url";
import asset_7_rubric from "../../../../examples/edge-cases/08-runaway-shopping-cart/rubric.json?url";
import asset_7_evidence from "../../../../examples/edge-cases/08-runaway-shopping-cart/result.json?url";
import asset_7_provenance from "../../../../examples/edge-cases/08-runaway-shopping-cart/site-provenance.json?url";
import asset_7_ambient from "../../../../examples/edge-cases/08-runaway-shopping-cart/ambient-sweep.json?url";
import asset_7_variations from "../../../../examples/edge-cases/08-runaway-shopping-cart/site-matches.json?url";
import asset_8_template from "../../../../examples/edge-cases/double-turn-mobility-scooter/scenario.template.json?url";
import asset_8_instance from "../../../../examples/edge-cases/double-turn-mobility-scooter/instance.json?url";
import asset_8_trace from "../../../../examples/edge-cases/double-turn-mobility-scooter/trace.json.gz?url";
import asset_8_rubric from "../../../../examples/edge-cases/double-turn-mobility-scooter/intent-rubric.json?url";
import asset_8_evidence from "../../../../examples/edge-cases/double-turn-mobility-scooter/review.json?url";
import asset_8_ambient from "../../../../examples/edge-cases/double-turn-mobility-scooter/ambient-matrix.json?url";
import asset_9_template from "../../../../examples/edge-cases/reversible-lane-stadium-egress/scenario.template.json?url";
import asset_9_instance from "../../../../examples/edge-cases/reversible-lane-stadium-egress/source.instance.json?url";
import asset_9_trace from "../../../../examples/edge-cases/reversible-lane-stadium-egress/source.trace.json.gz?url";
import asset_9_rubric from "../../../../examples/edge-cases/reversible-lane-stadium-egress/intent-rubric.json?url";
import asset_9_evidence from "../../../../examples/edge-cases/reversible-lane-stadium-egress/review.json?url";
import asset_9_ambient from "../../../../examples/edge-cases/reversible-lane-stadium-egress/ambient-matrix.json?url";

export const GENERATED_CAMPAIGN_ENTRIES: readonly GeneratedCampaignEntry[] = [
  { ...{"ordinal":1,"stableId":"edge-01-blind-chicane-emerging-worker-v1","slug":"blind-chicane-emerging-worker","title":"Blind Chicane and Emerging Worker","owner":"codex/edge-campaign-01-02","status":"baseline-and-ambient-verified","mapId":"belmont-research-center","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"not-run","rubric":"verified-evidence","provenance":"missing","diagnostics":[]}, assets: { "templateUrl": asset_0_template, "instanceUrl": asset_0_instance, "traceUrl": asset_0_trace, "rubricUrl": asset_0_rubric, "evidenceUrl": asset_0_evidence } },
  { ...{"ordinal":2,"stableId":"edge-02-bus-occluded-child-signalized-crossing-v1","slug":"bus-occluded-child-signalized-crossing","title":"Bus-Occluded Child at a Signalized Crossing","owner":"codex/edge-campaign-01-02","status":"baseline-and-ambient-intent-verified-platform-braking-blocker","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"not-run","rubric":"verified-evidence","provenance":"missing","diagnostics":[]}, assets: { "templateUrl": asset_1_template, "instanceUrl": asset_1_instance, "traceUrl": asset_1_trace, "rubricUrl": asset_1_rubric, "evidenceUrl": asset_1_evidence } },
  { ...{"ordinal":3,"stableId":"edge-03-contraflow-cyclist-garage-exit-v1","slug":"contraflow-cyclist-garage-exit","title":"Contraflow Cyclist at a Parking-Garage Exit","owner":"unknown","status":"simulated-ambient-verified","mapId":"yale-street","binding":"exact-matched-site","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_2_template, "instanceUrl": asset_2_instance, "traceUrl": asset_2_trace, "rubricUrl": asset_2_rubric, "evidenceUrl": asset_2_evidence, "provenanceUrl": asset_2_provenance, "ambientUrl": asset_2_ambient, "variationsUrl": asset_2_variations } },
  { ...{"ordinal":4,"stableId":"edge-04-wrong-way-sedan-blind-crest-v1","slug":"wrong-way-sedan-blind-crest","title":"Wrong-Way Sedan Beyond a Blind Crest","owner":"unknown","status":"simulated-ambient-verified","mapId":"easterbrook-discovery-school","binding":"exact-matched-site","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_3_template, "instanceUrl": asset_3_instance, "traceUrl": asset_3_trace, "rubricUrl": asset_3_rubric, "evidenceUrl": asset_3_evidence, "provenanceUrl": asset_3_provenance, "ambientUrl": asset_3_ambient, "variationsUrl": asset_3_variations } },
  { ...{"ordinal":5,"stableId":"edge-05-ambulance-gridlock-v1","slug":"05-ambulance-gridlocked-intersection","title":"Ambulance Through a Gridlocked Intersection","owner":"codex/edge_campaign_05_06","status":"strict_evidence_verified_needs_visual_review","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"not-run","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_4_template, "instanceUrl": asset_4_instance, "traceUrl": asset_4_trace, "rubricUrl": asset_4_rubric, "evidenceUrl": asset_4_evidence, "provenanceUrl": asset_4_provenance, "variationsUrl": asset_4_variations } },
  { ...{"ordinal":6,"stableId":"edge-06-dark-signal-human-control-v1","slug":"06-dark-signal-conflicting-human-control","title":"Dark Signal with Conflicting Human Control","owner":"codex/edge_campaign_05_06","status":"strict_evidence_verified_needs_visual_review","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"not-run","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_5_template, "instanceUrl": asset_5_instance, "traceUrl": asset_5_trace, "rubricUrl": asset_5_rubric, "evidenceUrl": asset_5_evidence, "provenanceUrl": asset_5_provenance, "variationsUrl": asset_5_variations } },
  { ...{"ordinal":7,"stableId":"edge-case-07-dooring-chain-tram","slug":"07-dooring-chain-tram","title":"07 · Dooring Chain Reaction Beside Tram Tracks","owner":"codex/edge-campaign-07-08","status":"behavior-and-ambient-combined-gate-verified-surrogate","mapId":"yale-street","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_6_template, "instanceUrl": asset_6_instance, "traceUrl": asset_6_trace, "rubricUrl": asset_6_rubric, "evidenceUrl": asset_6_evidence, "provenanceUrl": asset_6_provenance, "ambientUrl": asset_6_ambient, "variationsUrl": asset_6_variations } },
  { ...{"ordinal":8,"stableId":"edge-case-08-runaway-shopping-cart","slug":"08-runaway-shopping-cart","title":"08 · Runaway Shopping Cart in Rain and Glare","owner":"codex/edge-campaign-07-08","status":"behavior-and-ambient-combined-gate-verified-surrogate","mapId":"el-camino-road","binding":"pinned-behavioral-surrogate","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"present","diagnostics":[]}, assets: { "templateUrl": asset_7_template, "instanceUrl": asset_7_instance, "traceUrl": asset_7_trace, "rubricUrl": asset_7_rubric, "evidenceUrl": asset_7_evidence, "provenanceUrl": asset_7_provenance, "ambientUrl": asset_7_ambient, "variationsUrl": asset_7_variations } },
  { ...{"ordinal":9,"stableId":"edge-09-double-turn-mobility-scooter-v1","slug":"double-turn-mobility-scooter","title":"Double-Turn Conflict with a Mobility Scooter","owner":"edge_campaign_09_10","status":"baseline-and-ambient-verified","mapId":"el-camino-road","binding":"exact-matched-site","transfer":"1-verified-site","matchCount":1,"baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"missing","diagnostics":[]}, assets: { "templateUrl": asset_8_template, "instanceUrl": asset_8_instance, "traceUrl": asset_8_trace, "rubricUrl": asset_8_rubric, "evidenceUrl": asset_8_evidence, "ambientUrl": asset_8_ambient } },
  { ...{"ordinal":10,"stableId":"edge-10-reversible-lane-stadium-egress-v1","slug":"reversible-lane-stadium-egress","title":"Reversible Lane Transition During Stadium Egress","owner":"edge_campaign_09_10","status":"baseline-and-ambient-verified","mapId":"yale-street","binding":"exact-matched-site","transfer":"not-verified","baseline":"declared-evidence-runtime-check","identity":"exact-envelope","ambient":"verified-evidence","rubric":"verified-evidence","provenance":"missing","diagnostics":[]}, assets: { "templateUrl": asset_9_template, "instanceUrl": asset_9_instance, "traceUrl": asset_9_trace, "rubricUrl": asset_9_rubric, "evidenceUrl": asset_9_evidence, "ambientUrl": asset_9_ambient } }
];
export const GENERATED_CAMPAIGN_DIAGNOSTICS: readonly string[] = [];
export const GENERATED_CAMPAIGN_MANIFEST_COUNT = 5;
