"""Archetype grammar compiler — ArchetypeCell -> ScenarioTemplate v2.

NOVELTY / ANTI-OVERFITTING CONTRACT
Every constant in this module is keyed by an AXIS VALUE (topology, challenger, occlusion,
control, fault), never by an archetype id. There is no per-archetype code path anywhere.
An archetype is a point in the axis space; the compiler is a pure function of that point.
Adding an archetype adds a row of data, never a line of code.
"""
import numpy as np

KEYS = ['topology', 'challenger', 'occlusion', 'control', 'fault']
AXES = {'topology': ['rear_end', 'crossing_lateral', 'opposing_turn', 'merge_converge', 'encroach_lateral', 'static_obstacle', 'reverse_conflict'], 'challenger': ['car', 'truck', 'bus', 'motorcycle', 'cyclist', 'ped_adult', 'ped_child', 'animal', 'debris', 'worker'], 'occlusion': ['none', 'parked_row', 'large_vehicle', 'queue', 'geometry_curve', 'roadside_furniture'], 'control': ['open_road', 'uncontrolled_junction', 'stop_controlled', 'signalized', 'work_zone', 'school_zone'], 'fault': ['challenger_row_violation', 'challenger_sudden_decel', 'ego_gap_acceptance', 'late_reveal', 'challenger_unexpected_entry']}
TOPO_CHAL = {k: sorted(v) for k, v in {'rear_end': {'motorcycle', 'cyclist', 'truck', 'car', 'bus'}, 'crossing_lateral': {'ped_adult', 'motorcycle', 'cyclist', 'ped_child', 'truck', 'car', 'bus', 'animal'}, 'opposing_turn': {'motorcycle', 'cyclist', 'truck', 'car', 'bus'}, 'merge_converge': {'car', 'bus', 'motorcycle', 'truck'}, 'encroach_lateral': {'motorcycle', 'cyclist', 'worker', 'truck', 'car', 'bus'}, 'static_obstacle': {'debris', 'worker', 'truck', 'car', 'animal'}, 'reverse_conflict': {'ped_adult', 'car', 'ped_child', 'truck'}}.items()}
TOPO_FAULT = {k: sorted(v) for k, v in {'rear_end': {'challenger_sudden_decel', 'late_reveal'}, 'crossing_lateral': {'challenger_unexpected_entry', 'late_reveal', 'challenger_row_violation'}, 'opposing_turn': {'ego_gap_acceptance', 'challenger_row_violation'}, 'merge_converge': {'challenger_unexpected_entry', 'ego_gap_acceptance'}, 'encroach_lateral': {'challenger_unexpected_entry', 'late_reveal'}, 'static_obstacle': {'late_reveal'}, 'reverse_conflict': {'challenger_unexpected_entry', 'late_reveal'}}.items()}
CONTROL_TOPO = {k: sorted(v) for k, v in {'open_road': {'encroach_lateral', 'rear_end', 'static_obstacle', 'merge_converge', 'reverse_conflict', 'crossing_lateral'}, 'uncontrolled_junction': {'crossing_lateral', 'opposing_turn'}, 'stop_controlled': {'crossing_lateral', 'opposing_turn'}, 'signalized': {'crossing_lateral', 'opposing_turn'}, 'work_zone': {'encroach_lateral', 'static_obstacle', 'merge_converge'}, 'school_zone': {'crossing_lateral', 'static_obstacle'}}.items()}
CHAL = {'car': {'cls': 'car', 'cat': 'vehicle.sedan', 'vru': False, 'spd': 'clamp(0.9*lane.speedLimitKph,25,65)', 'dims': None}, 'truck': {'cls': 'truck', 'cat': 'vehicle.boxTruck', 'vru': False, 'spd': 'clamp(0.75*lane.speedLimitKph,20,55)'}, 'bus': {'cls': 'bus', 'cat': 'vehicle.cityBus', 'vru': False, 'spd': 'clamp(0.7*lane.speedLimitKph,18,50)'}, 'motorcycle': {'cls': 'motorcycle', 'cat': 'vehicle.motorcycle', 'vru': False, 'spd': 'clamp(1.0*lane.speedLimitKph,25,70)'}, 'cyclist': {'cls': 'bicycle', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph'}, 'ped_adult': {'cls': 'pedestrian', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph'}, 'ped_child': {'cls': 'pedestrian', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph'}, 'animal': {'cls': 'animal', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph'}, 'worker': {'cls': 'pedestrian', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph'}, 'debris': {'cls': 'static_object', 'cat': None, 'vru': True, 'spd': 'param.vruSpeedKph', 'static': True}}
VRU_SPD = {'cyclist': [10, 20], 'ped_adult': [4, 7], 'ped_child': [5, 9.5], 'animal': [6, 14], 'worker': [3, 6], 'debris': [0.1, 0.5]}
OCC = {'none': None, 'parked_row': {'cat': 'vehicle.suv', 'count': 3, 'spacing': 5.3, 'tFrac': -0.78, 'h': 1.78}, 'large_vehicle': {'cat': 'vehicle.boxTruck', 'count': 1, 'spacing': 0, 'tFrac': -0.72, 'h': 3.2}, 'queue': {'cat': 'vehicle.sedan', 'count': 4, 'spacing': 6.2, 'tFrac': -0.35, 'h': 1.5}, 'geometry_curve': {'cat': 'vehicle.boxTruck', 'count': 2, 'spacing': 6.0, 'tFrac': -0.8, 'h': 3.2}, 'roadside_furniture': {'cat': 'vehicle.suv', 'count': 2, 'spacing': 4.6, 'tFrac': -0.88, 'h': 1.9}}
OCC_FEATURE = {'geometry_curve': 'curve', 'parked_row': 'occlusion_zone', 'roadside_furniture': 'occlusion_zone', 'large_vehicle': None, 'queue': None, 'none': None}
CTRL = {'open_road': {'feature': None, 'signal': False}, 'uncontrolled_junction': {'feature': ['uncontrolled'], 'signal': False}, 'stop_controlled': {'feature': ['all_way_stop', 'minor_stop'], 'signal': False}, 'signalized': {'feature': ['signalized'], 'signal': True}, 'work_zone': {'feature': None, 'signal': False}, 'school_zone': {'feature': None, 'signal': False}}
TOPO = {'rear_end': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'relative_to', 'conflictS': None}, 'crossing_lateral': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'on_reference', 'conflictS': 125}, 'opposing_turn': {'metric': 'path_ttc', 'band': [0.3, 3.0], 'chal_kind': 'on_reference', 'conflictS': 125}, 'merge_converge': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'relative_to', 'conflictS': None}, 'encroach_lateral': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'on_reference', 'conflictS': 125}, 'static_obstacle': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'on_reference', 'conflictS': 125}, 'reverse_conflict': {'metric': 'ttc', 'band': [0.5, 2.5], 'chal_kind': 'on_reference', 'conflictS': 125}}
FAULT_RULES = {'challenger_row_violation': [('rules.yieldToVehicles', False), ('rules.obeySignals', False)], 'challenger_sudden_decel': [], 'ego_gap_acceptance': [], 'late_reveal': [('rules.yieldToVehicles', False), ('rules.collisionAvoidance', False)], 'challenger_unexpected_entry': [('rules.yieldToVehicles', False), ('rules.collisionAvoidance', False)]}
INLANE_TOPO = ['merge_converge', 'rear_end', 'static_obstacle']

CLIP = 14
WARM = 2
CONF = 125.0
EGO_SPD = 'clamp(0.7*lane.speedLimitKph,18,42)'
EGO_MAX_MPS = 11.666666666666666
