import type { Interaction, ScenarioTemplateV2, Verb } from '@uniscenarios/scenario-model';

export type ActorClass = ScenarioTemplateV2['roles'][number]['actor']['class'];
export type ActionFamily = 'vehicle' | 'pedestrian' | 'cyclist' | 'static';
export type ActionResource = 'longitudinal' | 'lateral' | 'indicator' | 'horn' | 'lights' | 'signal';
export interface ActionDefinition { readonly id: string; readonly label: string; readonly group: string; readonly verb: Verb; readonly target: Record<string, unknown>; readonly resource: ActionResource; readonly durationS: number; }

const speed = (id: string, label: string, target: Record<string, unknown>, durationS = 1): ActionDefinition => ({ id, label, group: 'Speed', verb: 'speed', target, resource: 'longitudinal', durationS });
const lateral = (id: string, label: string, verb: 'changeLane' | 'laneOffset' | 'route', target: Record<string, unknown>, durationS = 2): ActionDefinition => ({ id, label, group: 'Direction', verb, target, resource: 'lateral', durationS });
const signal = (id: string, label: string, key: string, value: unknown, resource: ActionResource): ActionDefinition => ({ id, label, group: 'Signals', verb: 'set', target: { key, value }, resource, durationS: .35 });

const VEHICLE: readonly ActionDefinition[] = [
  speed('accelerate', 'Accelerate', { mode: 'delta', deltaKph: 10 }), speed('decelerate', 'Decelerate', { mode: 'delta', deltaKph: -10 }), speed('brake_stop', 'Brake to stop', { mode: 'stop' }, 1.5), speed('resume', 'Resume default speed', { mode: 'resume' }), speed('target_speed', 'Set target speed', { mode: 'absolute', valueKph: 48 }),
  lateral('lane_left', 'Change lane left', 'changeLane', { mode: 'relative', dk: 1 }), lateral('lane_right', 'Change lane right', 'changeLane', { mode: 'relative', dk: -1 }), lateral('turn_left', 'Turn left', 'route', { mode: 'acquire', pose: { laneOffset: 1, s: 0, tFrac: 0, headingOffsetRad: 0 } }), lateral('turn_right', 'Turn right', 'route', { mode: 'acquire', pose: { laneOffset: -1, s: 0, tFrac: 0, headingOffsetRad: 0 } }), lateral('pull_over', 'Pull over', 'laneOffset', { tFrac: -.8, reference: 'lane_center' }, 3),
  signal('indicator_left', 'Left blinker', 'lights.indicator', 'left', 'indicator'), signal('indicator_right', 'Right blinker', 'lights.indicator', 'right', 'indicator'), signal('indicator_hazard', 'Hazard lights', 'lights.indicator', 'hazard', 'indicator'), signal('indicator_off', 'Blinkers off', 'lights.indicator', 'off', 'indicator'), signal('horn_on', 'Sound horn', 'audio.horn', true, 'horn'), signal('horn_off', 'Stop horn', 'audio.horn', false, 'horn'), signal('lights_on', 'Headlights on', 'lights.headlights', true, 'lights'), signal('lights_off', 'Headlights off', 'lights.headlights', false, 'lights'),
];
const PEDESTRIAN: readonly ActionDefinition[] = [
  speed('walk', 'Walk', { mode: 'absolute', valueKph: 5 }, .6), speed('wait', 'Wait', { mode: 'stop' }, .4), lateral('cross', 'Cross', 'route', { mode: 'acquire', pose: { laneOffset: 1, s: 0, tFrac: 0, headingOffsetRad: 0 } }, 3), speed('pace_faster', 'Walk faster', { mode: 'delta', deltaKph: 2 }), speed('pace_slower', 'Walk slower', { mode: 'delta', deltaKph: -2 }), lateral('direction_left', 'Turn left', 'route', { mode: 'acquire', pose: { laneOffset: 0, s: 0, tFrac: 0, headingOffsetRad: 1.570796 } }, .6), lateral('direction_right', 'Turn right', 'route', { mode: 'acquire', pose: { laneOffset: 0, s: 0, tFrac: 0, headingOffsetRad: -1.570796 } }, .6),
];
const CYCLIST: readonly ActionDefinition[] = [
  speed('cycle_faster', 'Pedal faster', { mode: 'delta', deltaKph: 5 }), speed('cycle_slower', 'Slow down', { mode: 'delta', deltaKph: -5 }), speed('cycle_stop', 'Stop', { mode: 'stop' }, 1.2), speed('cycle_resume', 'Resume default speed', { mode: 'resume' }), speed('cycle_target_speed', 'Set target speed', { mode: 'absolute', valueKph: 18 }), lateral('cycle_lane_left', 'Move left', 'changeLane', { mode: 'relative', dk: 1 }), lateral('cycle_lane_right', 'Move right', 'changeLane', { mode: 'relative', dk: -1 }), lateral('cycle_turn_left', 'Turn left', 'route', { mode: 'acquire', pose: { laneOffset: 1, s: 0, tFrac: 0, headingOffsetRad: 0 } }), lateral('cycle_turn_right', 'Turn right', 'route', { mode: 'acquire', pose: { laneOffset: -1, s: 0, tFrac: 0, headingOffsetRad: 0 } }), signal('cycle_signal_left', 'Signal left', 'pose.signal', 'left', 'signal'), signal('cycle_signal_right', 'Signal right', 'pose.signal', 'right', 'signal'), signal('cycle_signal_off', 'Lower hand signal', 'pose.signal', 'off', 'signal'),
];

export function actionFamily(actorClass: ActorClass, catalogId?: string): ActionFamily { if (actorClass === 'static_object') return 'static'; if (actorClass === 'pedestrian' || actorClass === 'animal') return 'pedestrian'; if (actorClass === 'bicycle' || actorClass === 'scooter' || /bicycle|cyclist/.test(catalogId ?? '')) return 'cyclist'; return 'vehicle'; }
export function actionsForActor(actorClass: ActorClass, catalogId?: string): readonly ActionDefinition[] { const family = actionFamily(actorClass, catalogId); return family === 'vehicle' ? VEHICLE : family === 'pedestrian' ? PEDESTRIAN : family === 'cyclist' ? CYCLIST : []; }
export function defaultSpeedKph(actorClass: ActorClass, catalogId?: string): number { const family = actionFamily(actorClass, catalogId); return family === 'vehicle' ? 48.28032 : family === 'cyclist' ? 18 : family === 'pedestrian' ? 5 : 0; }
export function actionResource(interaction: Interaction): ActionResource | null { if (interaction.verb === 'speed' || interaction.verb === 'gap') return 'longitudinal'; if (interaction.verb === 'changeLane' || interaction.verb === 'laneOffset' || interaction.verb === 'route') return 'lateral'; if (interaction.verb !== 'set') return null; const key = String(interaction.target.key); if (key === 'lights.indicator') return 'indicator'; if (key === 'audio.horn') return 'horn'; if (key === 'lights.headlights') return 'lights'; if (key === 'pose.signal') return 'signal'; return null; }
export function isActionCompatible(interaction: Interaction, actorClass: ActorClass, catalogId?: string): boolean { if (actionFamily(actorClass, catalogId) === 'static') return false; const resource = actionResource(interaction); if (!resource) return false; return actionsForActor(actorClass, catalogId).some((item) => item.verb === interaction.verb && item.resource === resource); }
export function definitionForInteraction(interaction: Interaction, actorClass: ActorClass, catalogId?: string): ActionDefinition | undefined { return actionsForActor(actorClass, catalogId).find((item) => item.verb === interaction.verb && JSON.stringify(item.target) === JSON.stringify(interaction.target)); }
export function interactionForAction(definition: ActionDefinition, actor: string, time: number, ordinal: number): Interaction { const start = Math.max(0, Number(time.toFixed(3))); return { id: `${definition.id}_${actor}_${ordinal}`.replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 64), actor, label: definition.label, trigger: { kind: 'at', t: start }, until: { kind: 'at', t: Number((start + Math.max(.1, definition.durationS)).toFixed(3)) }, verb: definition.verb, target: definition.target, ...(['speed', 'gap', 'changeLane', 'laneOffset'].includes(definition.verb) ? { dynamics: { shape: 'linear' as const, constraint: 'time' as const, value: definition.durationS } } : {}) } as Interaction; }
